# Generated by Django 3.0.5 on 2020-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200411_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
