# Generated by Django 3.0.5 on 2020-04-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200411_2116'),
        ('events', '0005_auto_20200411_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='employment',
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='data.Department'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_single',
            field=models.BooleanField(default=True, verbose_name='One day'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
