# Generated by Django 3.0.5 on 2020-04-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200414_2234'),
        ('events', '0006_auto_20200411_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='data.Country'),
        ),
    ]
