# Generated by Django 3.0.5 on 2020-04-11 06:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('the_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_info', to='data.Employment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='info', to='personnel.PersonnelType')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='personnel.PersonnelReport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
