# Generated by Django 3.0.5 on 2020-04-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200411_2116'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelreport',
            name='employment',
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel_info', to='data.Department'),
        ),
    ]
