# Generated by Django 3.0.5 on 2020-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20200412_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelreport',
            name='advisor',
            field=models.IntegerField(blank=True, null=True, verbose_name='KOICA 봉사단'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='참고사항'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='etc_v',
            field=models.IntegerField(blank=True, null=True, verbose_name='KOICA 봉사단'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='global_doctor',
            field=models.IntegerField(blank=True, null=True, verbose_name='KOICA 봉사단'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='kmco',
            field=models.IntegerField(blank=True, null=True, verbose_name='KOICA 봉사단'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='koica',
            field=models.IntegerField(blank=True, null=True, verbose_name='KOICA 직원'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='koica_admin',
            field=models.IntegerField(blank=True, null=True, verbose_name='일반 행정원'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='koica_v',
            field=models.IntegerField(blank=True, null=True, verbose_name='KOICA 봉사단'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='local_p',
            field=models.IntegerField(blank=True, null=True, verbose_name='봉사단 파트 현지고용원'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='local_v',
            field=models.IntegerField(blank=True, null=True, verbose_name='사무소 파트 현지고용원'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='p_codi',
            field=models.IntegerField(blank=True, null=True, verbose_name='개발협력 코디네이터'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='project_etc',
            field=models.IntegerField(blank=True, null=True, verbose_name='외부소속 프로젝트 인원'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='project_koica',
            field=models.IntegerField(blank=True, null=True, verbose_name='사무소 고용 프로젝트 인원'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='v_codi',
            field=models.IntegerField(blank=True, null=True, verbose_name='봉사단 코디네이터'),
        ),
        migrations.AddField(
            model_name='personnelreport',
            name='yp',
            field=models.IntegerField(blank=True, null=True, verbose_name='YP'),
        ),
    ]
