# Generated by Django 3.0.5 on 2020-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20200414_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelreport',
            name='advisor',
            field=models.IntegerField(blank=True, null=True, verbose_name='중장기 자문단'),
        ),
        migrations.AlterField(
            model_name='personnelreport',
            name='etc_v',
            field=models.IntegerField(blank=True, null=True, verbose_name='타 WFK봉사단(NIPA 등)'),
        ),
        migrations.AlterField(
            model_name='personnelreport',
            name='global_doctor',
            field=models.IntegerField(blank=True, null=True, verbose_name='글로벌 협력의사'),
        ),
        migrations.AlterField(
            model_name='personnelreport',
            name='kmco',
            field=models.IntegerField(blank=True, null=True, verbose_name='다자협력전문가'),
        ),
        migrations.AlterField(
            model_name='personnelreport',
            name='report_date',
            field=models.DateField(verbose_name='보고기준일'),
        ),
    ]
