# Generated by Django 3.0.5 on 2020-04-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200414_2234'),
        ('personnel', '0006_auto_20200414_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelreport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_report', to='data.Country'),
        ),
    ]
