# Generated by Django 3.0.5 on 2020-04-11 06:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django_countries.fields.CountryField(max_length=2)),
                ('korean', models.TextField(max_length='255')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('koica_code', models.CharField(max_length=255)),
                ('location', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('countries', models.ManyToManyField(blank=True, related_name='regions', to='data.Country')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('antecedents', models.ManyToManyField(blank=True, related_name='antecedents', to='data.Employment')),
                ('countries', models.ManyToManyField(blank=True, related_name='employment_detail', to='data.Country')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_detail', to='data.Employment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
