# Generated by Django 3.0.5 on 2020-04-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200411_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetail',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
