# Generated by Django 3.0.5 on 2020-04-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200411_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='data.Country'),
        ),
    ]
